import { ThinkOutput, PlanOutput, DirectOutput } from '@/types/pipeline'

export function exportToMarkdown(
  idea: string,
  think: Partial<ThinkOutput>,
  plan: Partial<PlanOutput>,
  direct: Partial<DirectOutput>
): string {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  let md = `# DIRECTOR'S BRIEF
**Project:** ${idea}
**Date:** ${date}
**Generated by:** CTE — Cinematic Thinking Engine

---

## ACT I — CINEMATIC ANALYSIS

`
  if (think.audience) {
    md += `### AUDIENCE
- **Primary:** ${think.audience.primary}
- **Psychographic:** ${think.audience.psychographic}
- **Why They Care:** ${think.audience.whyTheyCare}

`
  }
  if (think.emotion) {
    md += `### EMOTIONAL CONTRACT
- **Core Feeling:** ${think.emotion.coreFeeling}
- **Tension:** ${think.emotion.tension}
- **Catharsis:** ${think.emotion.catharsis}

`
  }
  if (think.narrativeDNA) {
    md += `### NARRATIVE DNA
- **Archetype:** ${think.narrativeDNA.archetype}
- **Structure:** ${think.narrativeDNA.structure}
- **Themes:** ${think.narrativeDNA.themes?.join(', ')}

`
  }
  if (think.visualDNA) {
    md += `### VISUAL DNA
- **Mood:** ${think.visualDNA.moodWords?.join(' · ')}
- **References:** ${think.visualDNA.referenceFilms?.join(', ')}
- **Signature Image:** ${think.visualDNA.signatureImage}

---

`
  }

  if (plan.logline) {
    md += `## ACT II — STORY PLAN

**LOGLINE:** ${plan.logline}

`
  }
  if (plan.acts) {
    for (const act of plan.acts) {
      md += `### ${act.name.toUpperCase()}
*${act.purpose}*

`
      for (const scene of act.scenes || []) {
        md += `**Scene ${scene.id}** [Intensity: ${scene.intensity}/10 · ${scene.pacing}]
${scene.summary}
*Emotional Beat:* ${scene.emotionalBeat}

`
      }
    }
  }
  if (plan.turningPoints?.length) {
    md += `### TURNING POINTS
${plan.turningPoints.map((tp, i) => `${i + 1}. ${tp}`).join('\n')}

---

`
  }

  if (direct.cinematography) {
    md += `## ACT III — VISUAL DIRECTION

### CINEMATOGRAPHY
- **Style:** ${direct.cinematography.style}
- **Lens:** ${direct.cinematography.lensPreference}
- **Lighting:** ${direct.cinematography.lighting}
- **Movement:** ${direct.cinematography.movement}

`
  }
  if (direct.colorPalette?.length) {
    md += `### COLOR PALETTE
${direct.colorPalette.map((c) => `- **${c.name}** \`${c.hex}\` — ${c.usage}`).join('\n')}

`
  }
  if (direct.shotList?.length) {
    md += `### SHOT LIST
${direct.shotList.map((s) => `**Scene ${s.scene} · ${s.shotType.toUpperCase()}** (${s.duration})
Framing: ${s.framing}
Movement: ${s.movement}
Mood: ${s.mood}`).join('\n\n')}

`
  }
  if (direct.aiImagePrompts?.length) {
    md += `### AI IMAGE PROMPTS
${direct.aiImagePrompts.map((p) => `**Scene ${p.scene}** [${p.aspectRatio}]
\`\`\`
${p.prompt}
\`\`\`
Negative: \`${p.negativePrompt}\``).join('\n\n')}

`
  }

  md += `---
*Generated by CTE — Cinematic Thinking Engine*`
  return md
}
